shell			zsh --login

# font_family		Go Mono
font_family Iosevka Fixed Slab ExtraLight Extended 
bold_font   Iosevka Fixed Slab Medium Extended
italic_font Iosevka Fixed Slab ExtraLight Oblique
# font_family Iosevka Slab Light Extended
# bold_font   Iosevka Slab Bold Extended
# italic_font Iosevka Slab Oblique Extended
#symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols
symbol_map U+1F600-U+1F64F Noto Color Emoji
font_size		13
# disable_ligatures	always
select_by_word_characters @-./_~:

tab_bar_style		separator
tab_separator		" \/ "
tab_activity_symbol	
map ctrl+t		new_tab
map ctrl+w		close_tab
map ctrl+page_down	next_tab
map ctrl+page_up	previous_tab
map ctrl+shift+t	select_tab

enable_layouts		tall
map alt+o		combine : new_window : goto_layout tall
map alt+y		close_window
map alt+j		previous_window
map alt+k		next_window
map alt+u		input_unicode_character
map alt+h       resize_window narrower
map alt+l       resize_window wider
