shell			zsh --login

include   ./EarlGrey.conf

# font_family		Go Mono
# font_family Iosevka Fixed Slab ExtraLight Extended 
# bold_font   Iosevka Fixed Slab Medium Extended
# italic_font Iosevka Fixed Slab ExtraLight Oblique
font_family Iosevka Fixed Slab ExtraLight
bold_font   Iosevka Fixed Slab Medium
# italic_font Iosevka Fixed Slab Oblique
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7  IosevkaTermSlab Nerd Font Light
symbol_map U+1F600-U+1F64F              IosevkaTermSlab Nerd Font Light
font_size		15
select_by_word_characters @-./_~:

tab_bar_style		separator
tab_separator		" ┋ "
tab_activity_symbol	！
map ctrl+t		new_tab
map ctrl+w		close_tab
map ctrl+page_down	next_tab
map ctrl+page_up	previous_tab
map ctrl+shift+t	select_tab
map alt+u		input_unicode_character
