# General
font_family		FiraCode Nerd Font
font_size		13
disable_ligatures	always
shell			zsh --login
#background_opacity	0.75
# Tab management
tab_bar_style		separator
tab_separator		" \/ "
tab_activity_symbol	
map ctrl+t		new_tab
map ctrl+w		close_tab
map ctrl+page_down	next_tab
map ctrl+page_up	previous_tab
map ctrl+shift+t	select_tab
# Window management
enable_layouts		tall
map alt+y		combine : new_window : goto_layout tall
map alt+h		close_window
map alt+j		previous_window
map alt+k		next_window
