# theme = "ubuntu"
theme = "monokai_pro_spectrum"

[keys.normal]
g = { k = "toggle_comments" }
"=" = ":fmt"

[keys.insert]
C-c = "normal_mode"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
