theme = "earl_grey"

[editor]
line-number = "relative"
true-color = true
bufferline = "multiple"
auto-format = false

[keys.normal]
"=" = ":fmt"
esc = ["collapse_selection", "keep_primary_selection"]
g = { P = ":pipe goprint" }

[keys.insert]
C-j = "normal_mode"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "→"
newline = "↩"

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "workspace-diagnostics"]
center = []
right = ["file-name", "separator", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
