# theme = "lady_grey"
theme = "earl_grey"

[editor]
auto-format = false
bufferline = "multiple"
line-number = "relative"
rulers = [80, 100]
shell = ["nu", "-c"]
true-color = true

[keys.normal]
"=" = ":fmt"
esc = ["collapse_selection", "keep_primary_selection"]
g = { P = ":pipe goprint" , b = [":pipe-to cat - o> /tmp/hx", ":sh hx-pickaxe"] }

[keys.insert]
C-j = "normal_mode"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "→"
newline = "↩"

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "position", "selections"]
center = []
right = ["file-name", "separator", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
