"comment" = { fg = "grey4", modifiers = ["italic"] }
"function" = { modifiers = ["bold"] }

"ui.background" = { bg = "bg" }
"ui.background.separator" = { fg = "fg" }

"ui.linenr" = { fg = "grey4" }
"ui.linenr.selected" = { fg = "blue" }

"ui.statusline" = { fg = "blue", bg = "grey1" }
"ui.statusline.inactive" = { fg = "fg", bg = "grey1", modifiers = ["dim"] }
"ui.statusline.normal" = { fg = "bg", bg = "cyan", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg", bg = "blue", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg", bg = "magenta", modifiers = ["bold"] }

"ui.popup" = { bg = "grey1" }
"ui.window" = { fg = "grey2" }
"ui.help" = { bg = "grey1", fg = "white" }

"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "fg" }

"ui.virtual" = { fg = "grey2" }
"ui.virtual.ruler" = {bg="grey2"}
"ui.virtual.indent-guide" = { fg = "grey2" }
"ui.virtual.inlay-hint" = { fg = "grey3" }

"ui.selection" = { bg = "grey3" }
"ui.selection.primary" = { bg = "grey3" }

"ui.cursor" = {fg="bg", bg = "blue" }
"ui.cursorline.primary" = { bg = "grey1" }

"ui.highlight" = { bg = "grey2" }

"ui.menu" = { fg = "white", bg = "grey1" }
"ui.menu.selected" = { fg = "bright_white", bg = "grey3" }
"ui.menu.scroll" = { fg = "grey4", bg = "grey1" }

"diagnostic.hint" = { underline = { color = "cyan", style = "curl" } }
"diagnostic.info" = { underline = { color = "magenta", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

warning = "yellow"
error = "red"
info = "magent"
hint = "cyan"

[palette]
bg = "#0f1014"
blue = "#aca1cf"
bright_blue = "#b9aeda"
bright_green = "#9dc6ac"
bright_white = "#cac9dd"
cyan = "#99bbe0"
fg = "#c9c7cd"
green = "#90b99f"
grey1 = "#1b1b1d"
grey2 = "#2a2a2d"
grey3 = "#3e3e43"
grey4 = "#57575f"
grey6 = "#9998a8"
grey7 = "#c1c0d4"
magenta = "#e29eca"
red = "#e78284"
white = "#cac9dd"
yellow = "#e5c890"
