"ui.text" = { fg = "#ffffff" }
"ui.background" = { bg = "#151515" }

"ui.selection" = { bg = "#303030" }
"ui.selection.primary" = { bg = "#303030" }
"ui.cursor.primary" = { bg = "#505050" }

"ui.linenr" = { fg = "#505050" }
"ui.linenr.selected" = { fg = "yellow0" }

"ui.window" = { bg = "#f0f0f0" }
"ui.popup" = { fg = "#909090", bg = "#050505" }
"ui.help" = { fg = "#909090", bg = "#050505" }
"ui.menu" = { fg = "#909090", bg = "#050505" }
"ui.menu.selected" = { bg = "#303030" }
"ui.bufferline.active" = { fg = "bg0", bg = "yellow0", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg1"

"comment" = { fg = "#707070", modifiers = ["italic"] }
"function" = { modifiers = ["bold"] }
"variable" = "#ffffff"
"variable.builtin" = "#ffffff"
"variable.parameter" = "#ffffff"
"variable.other.member" = "#ffffff"

"warning" = { fg = "yellow0" }
"error" = { fg = "red0" }
"info" = { fg = "blue0" }
"hint" = { fg = "#eeeeb3" }

"diagnostic.warning" = { underline = { color = "yellow0", style = "curl" } }
"diagnostic.error" = { underline = { color = "red0", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue0", style = "curl" } }
"diagnostic.hint" = { underline = { color = "#eeeeb3", style = "curl" } }

[palette]
bg0 = "#1d2021" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2" # main foreground
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984" # gray0

gray0 = "#a89984"
gray1 = "#928374"

red0 = "#cc241d" # neutral
red1 = "#fb4934" # bright
green0 = "#98971a"
green1 = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0 = "#458588"
blue1 = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0 = "#689d6a"
aqua1 = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
