[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
experimental = { useFlatConfig = false }
nodePath = ""
problems = { shortenToSingleLine = false }
rulesCustomizations = []
run = "onType"
validate = "on"

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "typescript"
formatter = { command = "biome", args = ["format", "--stdin-file-path=fake.ts"] }
language-servers = [
  { name = "eslint", except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "javascript"
formatter = { command = "biome", args = ["format", "--stdin-file-path=fake.js"] }
language-servers = [
  { name = "eslint", except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "tsx"
formatter = { command = "biome", args = ["format", "--stdin-file-path=fake.tsx"] }
language-servers = [
  { name = "eslint", except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "json"
formatter = { command = "biome", args = ["format", "--stdin-file-path=fake.json"] }
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome",
]

[[language]]
name = "bash"
formatter = { command = "shfmt" }
