[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
experimental = { useFlatConfig = false }
nodePath = ""
problems = { shortenToSingleLine = false }
rulesCustomizations = []
run = "onType"
validate = "on"

[[language]]
name = "typescript"
formatter = { command = "dprint", args = ["fmt", "--stdin", "ts"] }
language-servers = [
  { name = "eslint", except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
]

[[language]]
name = "tsx"
formatter = { command = "dprint", args = ["fmt", "--stdin", "tsx"] }
language-servers = [
  { name = "eslint", except-features = ["format"] },
  { name = "typescript-language-server", except-features = ["format"] },
]

[[language]]
name = "json"
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }

[[language]]
name = "toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }
